/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param quantity
 * @param administrationUnit
 * @param unit
 */

data class AdministrationQuantity (


    val quantity: kotlin.Double? = null,


    val administrationUnit: CodeStubDto? = null,


    val unit: kotlin.String? = null

)

