/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param docSeq 
 * @param verseSeq 
 * @param documentId 
 * @param path 
 */

data class AgreementAppendixDto (

    
    val docSeq: kotlin.Int? = null,

    
    val verseSeq: kotlin.Int? = null,

    
    val documentId: kotlin.String? = null,

    
    val path: kotlin.String? = null

)

