/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param id
 * @param blackTriangle
 * @param ampps
 * @param components
 * @param rev
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param from
 * @param to
 * @param code
 * @param vmp
 * @param officialName
 * @param status
 * @param name
 * @param medicineType
 * @param company
 * @param abbreviatedName
 * @param proprietarySuffix
 * @param prescriptionName
 */

data class AmpDto (


    val id: kotlin.String,


    val blackTriangle: kotlin.Boolean,


    val ampps: kotlin.collections.List<AmppDto> = emptyList(),


    val components: kotlin.collections.List<AmpComponentDto> = emptyList(),


    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val code: kotlin.String? = null,


    val vmp: VmpStubDto? = null,


    val officialName: kotlin.String? = null,


    val status: AmpDto.Status? = null,


    val name: SamTextDto? = null,


    val medicineType: AmpDto.MedicineType? = null,


    val company: CompanyDto? = null,


    val abbreviatedName: SamTextDto? = null,


    val proprietarySuffix: SamTextDto? = null,


    val prescriptionName: SamTextDto? = null

) {

    /**
     *
     *
     * Values: aUTHORIZED,sUSPENDED,rEVOKED
     */
    enum class Status(val value: kotlin.String) {
        aUTHORIZED("AUTHORIZED"),
        sUSPENDED("SUSPENDED"),
        rEVOKED("REVOKED");
    }
    /**
     *
     *
     * Values: aLLOPATHIC,hOMEOPATHIC
     */
    enum class MedicineType(val value: kotlin.String) {
        aLLOPATHIC("ALLOPATHIC"),
        hOMEOPATHIC("HOMEOPATHIC");
    }
}

