/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param orphan
 * @param atcs
 * @param dmpps
 * @param from
 * @param to
 * @param index
 * @param ctiExtended
 * @param leafletLink
 * @param spcLink
 * @param rmaPatientLink
 * @param rmaProfessionalLink
 * @param parallelCircuit
 * @param parallelDistributor
 * @param packMultiplier
 * @param packAmount
 * @param packDisplayValue
 * @param status
 * @param crmLink
 * @param deliveryModusCode
 * @param deliveryModus
 * @param deliveryModusSpecificationCode
 * @param deliveryModusSpecification
 * @param dhpcLink
 * @param distributorCompany
 * @param singleUse
 * @param speciallyRegulated
 * @param abbreviatedName
 * @param prescriptionName
 * @param note
 * @param posologyNote
 * @param noGenericPrescriptionReasons
 * @param exFactoryPrice
 * @param reimbursementCode
 * @param definedDailyDose
 * @param officialExFactoryPrice
 * @param realExFactoryPrice
 * @param pricingInformationDecisionDate
 * @param components
 * @param commercializations
 * @param supplyProblems
 * @param vaccineIndicationCodes
 */

data class AmppDto (


    val orphan: kotlin.Boolean,


    val atcs: kotlin.collections.List<AtcDto> = emptyList(),


    val dmpps: kotlin.collections.List<DmppDto> = emptyList(),


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val index: kotlin.Double? = null,


    val ctiExtended: kotlin.String? = null,


    val leafletLink: SamTextDto? = null,


    val spcLink: SamTextDto? = null,


    val rmaPatientLink: SamTextDto? = null,


    val rmaProfessionalLink: SamTextDto? = null,


    val parallelCircuit: kotlin.Int? = null,


    val parallelDistributor: kotlin.String? = null,


    val packMultiplier: kotlin.Int? = null,


    val packAmount: QuantityDto? = null,


    val packDisplayValue: kotlin.String? = null,


    val status: AmppDto.Status? = null,


    val crmLink: SamTextDto? = null,


    val deliveryModusCode: kotlin.String? = null,


    val deliveryModus: SamTextDto? = null,


    val deliveryModusSpecificationCode: kotlin.String? = null,


    val deliveryModusSpecification: SamTextDto? = null,


    val dhpcLink: SamTextDto? = null,


    val distributorCompany: CompanyDto? = null,


    val singleUse: kotlin.Boolean? = null,


    val speciallyRegulated: kotlin.Int? = null,


    val abbreviatedName: SamTextDto? = null,


    val prescriptionName: SamTextDto? = null,


    val note: SamTextDto? = null,


    val posologyNote: SamTextDto? = null,


    val noGenericPrescriptionReasons: kotlin.collections.List<SamTextDto>? = null,


    val exFactoryPrice: kotlin.Double? = null,


    val reimbursementCode: kotlin.Int? = null,


    val definedDailyDose: QuantityDto? = null,


    val officialExFactoryPrice: kotlin.Double? = null,


    val realExFactoryPrice: kotlin.Double? = null,


    val pricingInformationDecisionDate: kotlin.Long? = null,


    val components: kotlin.collections.List<AmppComponentDto>? = null,


    val commercializations: kotlin.collections.List<CommercializationDto>? = null,


    val supplyProblems: kotlin.collections.List<SupplyProblemDto>? = null,


    val vaccineIndicationCodes: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     *
     *
     * Values: aUTHORIZED,sUSPENDED,rEVOKED
     */
    enum class Status(val value: kotlin.String) {
        aUTHORIZED("AUTHORIZED"),
        sUSPENDED("SUSPENDED"),
        rEVOKED("REVOKED");
    }
}

