/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * Encrypted and time-limited Authentication tokens used for inter-applications authentication
 *
 * @param token Encrypted token
 * @param creationTime Validity starting time of the token
 * @param validity Token validity in seconds
 */

data class AuthenticationTokenDto (

    /* Encrypted token */

    val token: kotlin.String,

    /* Validity starting time of the token */

    val creationTime: kotlin.Long,

    /* Token validity in seconds */

    val validity: kotlin.Long

)

