/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * A code is an item from a codification system that qualifies the content of this entity. SNOMED-CT, ICPC-2 or ICD-10 codifications systems can be used for codes
 *
 * @param id
 * @param context
 * @param type
 * @param code
 * @param version
 * @param label
 */

data class CodeStubDto (


    val id: kotlin.String? = null,


    val context: kotlin.String? = null,


    val type: kotlin.String? = null,


    val code: kotlin.String? = null,


    val version: kotlin.String? = null,


    val label: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)

