/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param id
 * @param context
 * @param type
 * @param code
 * @param version
 * @param label
 */

data class CodeStub (


    val id: kotlin.String,


    val context: kotlin.String? = null,


    val type: kotlin.String? = null,


    val code: kotlin.String? = null,


    val version: kotlin.String? = null,


    val label: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)

