/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param from
 * @param to
 * @param authorisationNr
 * @param vatNr
 * @param europeanNr
 * @param denomination
 * @param legalForm
 * @param building
 * @param streetName
 * @param streetNum
 * @param postbox
 * @param postcode
 * @param city
 * @param countryCode
 * @param phone
 * @param language
 * @param website
 */

data class CompanyDto (


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val authorisationNr: kotlin.String? = null,


    val vatNr: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,


    val europeanNr: kotlin.String? = null,


    val denomination: kotlin.String? = null,


    val legalForm: kotlin.String? = null,


    val building: kotlin.String? = null,


    val streetName: kotlin.String? = null,


    val streetNum: kotlin.String? = null,


    val postbox: kotlin.String? = null,


    val postcode: kotlin.String? = null,


    val city: kotlin.String? = null,


    val countryCode: kotlin.String? = null,


    val phone: kotlin.String? = null,


    val language: kotlin.String? = null,


    val website: kotlin.String? = null

)

