/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * Information contained in the service. Content is localized, using ISO language code as key
 *
 * @param stringValue
 * @param numberValue
 * @param booleanValue
 * @param instantValue
 * @param fuzzyDateValue Value as date. The format could have a all three (day, month and year) or values on any of these three, whatever is known.
 * @param binaryValue
 * @param documentId Linked document.
 * @param measureValue
 * @param medicationValue
 * @param timeSeries
 * @param compoundValue
 * @param ratio
 * @param range
 */

data class ContentDto (


    val stringValue: kotlin.String? = null,


    val numberValue: kotlin.Double? = null,


    val booleanValue: kotlin.Boolean? = null,


    val instantValue: java.time.OffsetDateTime? = null,

    /* Value as date. The format could have a all three (day, month and year) or values on any of these three, whatever is known. */

    val fuzzyDateValue: kotlin.Long? = null,


    val binaryValue: ByteArray? = null,

    /* Linked document. */

    val documentId: kotlin.String? = null,


    val measureValue: MeasureDto? = null,


    val medicationValue: MedicationDto? = null,


    val timeSeries: TimeSeriesDto? = null,


    val compoundValue: kotlin.collections.List<ServiceDto>? = null,


    val ratio: kotlin.collections.List<MeasureDto>? = null,


    val range: kotlin.collections.List<MeasureDto>? = null

)

