/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param regimeType
 * @param from
 * @param to
 * @param feeAmount
 */

data class CopaymentDto (


    val regimeType: kotlin.Int? = null,


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val feeAmount: kotlin.String? = null

)

