/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * initialisationData is an object that contains the initial replications (target must be an internalTarget of value base, healthdata or patient) and the users and healthcare parties to be created
 *
 * @param users
 * @param healthcareParties
 * @param replication
 */

data class DatabaseInitialisationDto (


    val users: kotlin.collections.List<UserDto>? = null,


    val healthcareParties: kotlin.collections.List<HealthcarePartyDto>? = null,


    val replication: ReplicationDto? = null

)

