/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * When a document needs to be encrypted, the responsible generates a cryptographically random master key (different from the delegation key, never to appear in clear anywhere in the db. He/she encrypts it using his own AES exchange key and stores it as a delegation
 *
 * @param tags 
 * @param owner 
 * @param delegatedTo 
 * @param key 
 */

data class DelegationDto (

    
    val tags: kotlin.collections.List<kotlin.String> = emptyList(),

    
    val owner: kotlin.String? = null,

    
    val delegatedTo: kotlin.String? = null,

    
    val key: kotlin.String? = null

)

