/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param left
 * @param top
 * @param width
 * @param height
 * @param multiline
 * @param labelPosition
 * @param readOnly
 * @param defaultValue
 * @param key
 */

data class Editor (


    val left: kotlin.Double? = null,


    val top: kotlin.Double? = null,


    val width: kotlin.Double? = null,


    val height: kotlin.Double? = null,


    val multiline: kotlin.Boolean? = null,


    val labelPosition: Editor.LabelPosition? = null,


    val readOnly: kotlin.Boolean? = null,


    val defaultValue: kotlin.Any? = null,


    val key: kotlin.String? = null

) {

    /**
     *
     *
     * Values: up,down,left,right
     */
    enum class LabelPosition(val value: kotlin.String) {
        up("Up"),
        down("Down"),
        left("Left"),
        right("Right");
    }
}

