/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param id
 * @param entity
 * @param rev
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param userId
 * @param descr
 * @param keywords
 * @param entityType
 * @param subType
 * @param defaultTemplate
 */

data class EntityTemplateDto (


    val id: kotlin.String,


    val entity: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>> = emptyList(),


    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,


    val userId: kotlin.String? = null,


    val descr: kotlin.String? = null,


    val keywords: kotlin.collections.Set<kotlin.String>? = null,


    val entityType: kotlin.String? = null,


    val subType: kotlin.String? = null,


    val defaultTemplate: kotlin.Boolean? = null

)

