/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * List of episodes of occurrences of the healthcare element.
 *
 * @param id
 * @param name
 * @param comment
 * @param startDate
 * @param endDate
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class EpisodeDto (


    val id: kotlin.String,


    val name: kotlin.String? = null,


    val comment: kotlin.String? = null,


    val startDate: kotlin.Long? = null,


    val endDate: kotlin.Long? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */

    val encryptedSelf: kotlin.String? = null

)

