/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * Financial information (Bank, bank account) used to reimburse the patient.
 *
 * @param preferredFiiForPartners 
 * @param name 
 * @param key 
 * @param bankAccount 
 * @param bic 
 * @param proxyBankAccount 
 * @param proxyBic 
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class FinancialInstitutionInformationDto (

    
    val preferredFiiForPartners: kotlin.collections.List<kotlin.String> = emptyList(),

    
    val name: kotlin.String? = null,

    
    val key: kotlin.String? = null,

    
    val bankAccount: kotlin.String? = null,

    
    val bic: kotlin.String? = null,

    
    val proxyBankAccount: kotlin.String? = null,

    
    val proxyBic: kotlin.String? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */
    
    val encryptedSelf: kotlin.String? = null

)

