/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * 
 *
 * @param valorisations 
 * @param code 
 * @param flatRateType 
 * @param label 
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class FlatRateTarificationDto (

    
    val valorisations: kotlin.collections.List<ValorisationDto> = emptyList(),

    
    val code: kotlin.String? = null,

    
    val flatRateType: FlatRateTarificationDto.FlatRateType? = null,

    
    val label: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */
    
    val encryptedSelf: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: physician,physiotherapist,nurse,ptd
     */
    enum class FlatRateType(val value: kotlin.String) {
        physician("physician"),
        physiotherapist("physiotherapist"),
        nurse("nurse"),
        ptd("ptd");
    }
}

