/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param name
 * @param width
 * @param height
 * @param descr
 * @param tag
 * @param guid
 * @param group
 * @param sections
 * @param importedServiceXPaths
 */

data class FormLayout (


    val name: kotlin.String? = null,


    val width: kotlin.Double? = null,


    val height: kotlin.Double? = null,


    val descr: kotlin.String? = null,


    val tag: Tag? = null,


    val guid: kotlin.String? = null,


    val group: kotlin.String? = null,


    val sections: kotlin.collections.List<FormSection>? = null,


    val importedServiceXPaths: kotlin.collections.List<kotlin.String>? = null

)

