/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param planninfForAnyDoctor 
 * @param planningForDelegate 
 * @param planningForPatientDoctor 
 * @param planningForMe 
 * @param codedDelayInDays 
 * @param repetitions 
 * @param repetitionsUnit 
 * @param descr 
 */

data class FormPlanning (

    
    val planninfForAnyDoctor: kotlin.Boolean? = null,

    
    val planningForDelegate: kotlin.Boolean? = null,

    
    val planningForPatientDoctor: kotlin.Boolean? = null,

    
    val planningForMe: kotlin.Boolean? = null,

    
    val codedDelayInDays: kotlin.Int? = null,

    
    val repetitions: kotlin.Int? = null,

    
    val repetitionsUnit: kotlin.Int? = null,

    
    val descr: kotlin.String? = null

)

