/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * 
 *
 * @param id 
 * @param properties Extra properties for the fem. Those properties are typed (see class Property)
 * @param rev 
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param name 
 * @param startDate 
 * @param endDate 
 * @param status 
 * @param logs 
 * @param userId 
 * @param startKey 
 * @param startKeyDocId 
 * @param processCount 
 */

data class FrontEndMigrationDto (

    
    val id: kotlin.String,

    /* Extra properties for the fem. Those properties are typed (see class Property) */
    
    val properties: kotlin.collections.List<PropertyStubDto> = emptyList(),

    
    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */
    
    val deletionDate: kotlin.Long? = null,

    
    val name: kotlin.String? = null,

    
    val startDate: kotlin.Long? = null,

    
    val endDate: kotlin.Long? = null,

    
    val status: FrontEndMigrationDto.Status? = null,

    
    val logs: kotlin.String? = null,

    
    val userId: kotlin.String? = null,

    
    val startKey: kotlin.String? = null,

    
    val startKeyDocId: kotlin.String? = null,

    
    val processCount: kotlin.Long? = null

) {

    /**
     * 
     *
     * Values: sTARTED,pAUSED,eRROR,sUCCESS
     */
    enum class Status(val value: kotlin.String) {
        sTARTED("STARTED"),
        pAUSED("PAUSED"),
        eRROR("ERROR"),
        sUCCESS("SUCCESS");
    }
}

