/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * This class represents a coverage of a patient by an insurance during a period or time.
 *
 * @param parameters Insurance extra parameters.
 * @param hospitalisation Is hospitalization covered.
 * @param ambulatory Is outpatient care covered.
 * @param dental Is dental care covered.
 * @param identificationNumber Identification number of the patient at the insurance.
 * @param insuranceId Id of the Insurance.
 * @param startDate Start date of the coverage (YYYYMMDD).
 * @param endDate End date of the coverage (YYYYMMDD).
 * @param titularyId UUID of the contact person who is the policyholder of the insurance (when the patient is covered by the insurance of a third person).
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class InsurabilityDto (

    /* Insurance extra parameters. */

    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String> = emptyMap(),

    /* Is hospitalization covered. */

    val hospitalisation: kotlin.Boolean? = null,

    /* Is outpatient care covered. */

    val ambulatory: kotlin.Boolean? = null,

    /* Is dental care covered. */

    val dental: kotlin.Boolean? = null,

    /* Identification number of the patient at the insurance. */

    val identificationNumber: kotlin.String? = null,

    /* Id of the Insurance. */

    val insuranceId: kotlin.String? = null,

    /* Start date of the coverage (YYYYMMDD). */

    val startDate: kotlin.Long? = null,

    /* End date of the coverage (YYYYMMDD). */

    val endDate: kotlin.Long? = null,

    /* UUID of the contact person who is the policyholder of the insurance (when the patient is covered by the insurance of a third person). */

    val titularyId: kotlin.String? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */

    val encryptedSelf: kotlin.String? = null

)

