/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param id
 * @param name
 * @param privateInsurance
 * @param hospitalisationInsurance
 * @param ambulatoryInsurance
 * @param address
 * @param rev
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param code
 * @param agreementNumber
 * @param parent
 */

data class InsuranceDto (


    val id: kotlin.String,


    val name: kotlin.collections.Map<kotlin.String, kotlin.String> = emptyMap(),


    val privateInsurance: kotlin.Boolean,


    val hospitalisationInsurance: kotlin.Boolean,


    val ambulatoryInsurance: kotlin.Boolean,


    val address: AddressDto,


    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,


    val code: kotlin.String? = null,


    val agreementNumber: kotlin.String? = null,


    val parent: kotlin.String? = null

)

