/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param invoicingYear
 * @param invoicingMonth
 * @param invoices
 * @param fileRef
 * @param batchRef
 * @param ioFederationCode
 * @param uniqueSendNumber
 * @param sender
 * @param numericalRef
 */

data class InvoicesBatch (


    val invoicingYear: kotlin.Int = 0,


    val invoicingMonth: kotlin.Int = 0,


    val invoices: kotlin.collections.List<EfactInvoice> = emptyList(),


    val fileRef: kotlin.String? = null,


    val batchRef: kotlin.String? = null,


    val ioFederationCode: kotlin.String? = null,


    val uniqueSendNumber: kotlin.Long? = null,


    val sender: InvoiceSender? = null,


    val numericalRef: kotlin.Long? = null

)

