/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param beginDate
 * @param endDate
 * @param patientLanguage
 * @param incapacityType
 * @param incapacityReason
 * @param outOfHomeAllowed
 * @param author
 * @param patient
 * @param certificateDate
 * @param contentDate
 * @param diagnosisICPC
 * @param diagnosisICD
 * @param diagnosisDescr
 */

data class MedexInfoDto (


    val beginDate: kotlin.Long,


    val endDate: kotlin.Long,


    val patientLanguage: kotlin.String = "fr",


    val incapacityType: kotlin.String = "incapacity",


    val incapacityReason: kotlin.String = "sickness",


    val outOfHomeAllowed: kotlin.Boolean,


    val author: HealthcarePartyDto? = null,


    val patient: PatientDto? = null,


    val certificateDate: kotlin.Long? = null,


    val contentDate: kotlin.Long? = null,


    val diagnosisICPC: kotlin.String? = null,


    val diagnosisICD: kotlin.String? = null,


    val diagnosisDescr: kotlin.String? = null

)

