/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param ids
 * @param time
 * @param status
 * @param userId
 */

data class MessagesReadStatusUpdate (

    
    val ids: kotlin.collections.List<kotlin.String>? = null,

    
    val time: kotlin.Long? = null,

    
    val status: kotlin.Boolean? = null,

    
    val userId: kotlin.String? = null

)

