/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * If permission to modify patient data is granted or revoked
 *
 * @param grants Granted permissions.
 * @param revokes Revoked permissions.
 */

data class PermissionDto (

    /* Granted permissions. */

    val grants: kotlin.collections.List<PermissionItemDto> = emptyList(),

    /* Revoked permissions. */

    val revokes: kotlin.collections.List<PermissionItemDto> = emptyList()

)

