/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * Non preferred name information of a person
 *
 * @param firstNames Given names (not always 'first'). Includes middle names. This repeating element order: Given Names appear in the correct order for presenting the name
 * @param prefix Parts that come before the name. This repeating element order: Prefixes appear in the correct order for presenting the name
 * @param suffix Parts that come after the name. This repeating element order: Suffixes appear in the correct order for presenting the name
 * @param lastName Family name (often called 'Surname')
 * @param start Starting date of time period when name is/was valid for use. Date encoded as a fuzzy date on 8 positions (YYYYMMDD)
 * @param end Ending date of time period when name is/was valid for use. Date encoded as a fuzzy date on 8 positions (YYYYMMDD)
 * @param text Text representation of the full name
 * @param use What is the use of this name
 */

data class PersonNameDto (

    /* Given names (not always 'first'). Includes middle names. This repeating element order: Given Names appear in the correct order for presenting the name */
    
    val firstNames: kotlin.collections.List<kotlin.String> = emptyList(),

    /* Parts that come before the name. This repeating element order: Prefixes appear in the correct order for presenting the name */
    
    val prefix: kotlin.collections.List<kotlin.String> = emptyList(),

    /* Parts that come after the name. This repeating element order: Suffixes appear in the correct order for presenting the name */
    
    val suffix: kotlin.collections.List<kotlin.String> = emptyList(),

    /* Family name (often called 'Surname') */
    
    val lastName: kotlin.String? = null,

    /* Starting date of time period when name is/was valid for use. Date encoded as a fuzzy date on 8 positions (YYYYMMDD) */
    
    val start: kotlin.Long? = null,

    /* Ending date of time period when name is/was valid for use. Date encoded as a fuzzy date on 8 positions (YYYYMMDD) */
    
    val end: kotlin.Long? = null,

    /* Text representation of the full name */
    
    val text: kotlin.String? = null,

    /* What is the use of this name */
    
    val use: PersonNameDto.Use? = null

) {

    /**
     * What is the use of this name
     *
     * Values: usual,official,temp,nickname,anonymous,maiden,old,other
     */
    enum class Use(val value: kotlin.String) {
        usual("usual"),
        official("official"),
        temp("temp"),
        nickname("nickname"),
        anonymous("anonymous"),
        maiden("maiden"),
        old("old"),
        other("other");
    }
}

