/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param standardForms
 * @param id
 * @param code
 * @param name
 */

data class PharmaceuticalFormStubDto (


    val standardForms: kotlin.collections.List<CodeStubDto> = emptyList(),


    val id: kotlin.String? = null,


    val code: kotlin.String? = null,


    val name: SamTextDto? = null

)

