/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param identifier
 * @param type
 */

data class PropertyTypeStubDto (


    val identifier: kotlin.String? = null,


    val type: PropertyTypeStubDto.Type? = null

) {

    /**
     *
     *
     * Values: bOOLEAN,iNTEGER,dOUBLE,sTRING,dATE,cLOB,jSON
     */
    enum class Type(val value: kotlin.String) {
        bOOLEAN("BOOLEAN"),
        iNTEGER("INTEGER"),
        dOUBLE("DOUBLE"),
        sTRING("STRING"),
        dATE("DATE"),
        cLOB("CLOB"),
        jSON("JSON");
    }
}

