/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param date
 * @param dayNumber
 * @param weekday
 * @param dayPeriod
 * @param timeOfDay
 * @param administratedQuantity
 */

data class RegimenItemDto (


    val date: kotlin.Long? = null,


    val dayNumber: kotlin.Int? = null,


    val weekday: Weekday? = null,


    val dayPeriod: CodeStubDto? = null,


    val timeOfDay: kotlin.Long? = null,


    val administratedQuantity: AdministrationQuantity? = null

)

