/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param active
 * @param running
 * @param pendingFrom
 * @param pendingTo
 */

data class ReplicationInfoDto (

    
    val active: kotlin.Boolean,

    
    val running: kotlin.Boolean,

    
    val pendingFrom: kotlin.Int? = null,

    
    val pendingTo: kotlin.Int? = null

)

