/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * List of all services provided to the patient under a given contact which is linked by this sub-contact to other structuring elements.
 *
 * @param serviceId
 */

data class ServiceLinkDto (


    val serviceId: kotlin.String? = null

)

