/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param intendedcds
 * @param deliveredcds
 * @param intendedname
 * @param deliveredname
 * @param productId
 */

data class SubstanceproductDto (


    val intendedcds: kotlin.collections.List<CodeStubDto> = emptyList(),


    val deliveredcds: kotlin.collections.List<CodeStubDto> = emptyList(),


    val intendedname: kotlin.String? = null,


    val deliveredname: kotlin.String? = null,


    val productId: kotlin.String? = null

)

