/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param filterKey
 * @param filterValue
 * @param entityClass
 * @param fieldValue
 * @param fieldDisplay
 */

data class Suggest (


    val filterKey: kotlin.String? = null,


    val filterValue: kotlin.String? = null,


    val entityClass: kotlin.String? = null,


    val fieldValue: kotlin.String? = null,


    val fieldDisplay: kotlin.String? = null

)

