/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param services
 * @param healthElements
 * @param partnerships
 * @param patientHealthcareParties
 */

data class SumehrContentDto (


    val services: kotlin.collections.List<ServiceDto>? = null,


    val healthElements: kotlin.collections.List<HealthElementDto>? = null,


    val partnerships: kotlin.collections.List<PartnershipDto>? = null,


    val patientHealthcareParties: kotlin.collections.List<PatientHealthCarePartyDto>? = null

)

