/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * A high frequency time-series containing the ts in ms from the start (double) and the values
 *
 * @param fields
 * @param samples
 * @param min
 * @param max
 * @param mean
 * @param median
 * @param variance
 */

data class TimeSeriesDto (


    val fields: kotlin.collections.List<kotlin.String> = emptyList(),


    val samples: kotlin.collections.List<kotlin.collections.List<kotlin.Double>> = emptyList(),


    val min: kotlin.collections.List<kotlin.Double> = emptyList(),


    val max: kotlin.collections.List<kotlin.Double> = emptyList(),


    val mean: kotlin.collections.List<kotlin.Double> = emptyList(),


    val median: kotlin.collections.List<kotlin.Double> = emptyList(),


    val variance: kotlin.collections.List<kotlin.Double> = emptyList()

)

