/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param days
 * @param hours
 * @param recurrenceTypes
 * @param homeVisit
 * @param publicTimeTableItem
 * @param acceptsNewPatient
 * @param unavailable
 * @param calendarItemTypeId
 * @param placeId
 */

data class TimeTableItemDto (


    val days: kotlin.collections.List<kotlin.String> = emptyList(),


    val hours: kotlin.collections.List<TimeTableHourDto> = emptyList(),


    val recurrenceTypes: kotlin.collections.List<kotlin.String> = emptyList(),


    val homeVisit: kotlin.Boolean,


    val publicTimeTableItem: kotlin.Boolean,


    val acceptsNewPatient: kotlin.Boolean,


    val unavailable: kotlin.Boolean,


    val calendarItemTypeId: kotlin.String? = null,


    val placeId: kotlin.String? = null

)

