/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param startOfValidity 
 * @param endOfValidity 
 * @param predicate 
 * @param totalAmount 
 * @param reimbursement 
 * @param patientIntervention 
 * @param doctorSupplement 
 * @param vat 
 * @param label 
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class ValorisationDto (

    
    val startOfValidity: kotlin.Long? = null,

    
    val endOfValidity: kotlin.Long? = null,

    
    val predicate: kotlin.String? = null,

    
    val totalAmount: kotlin.Double? = null,

    
    val reimbursement: kotlin.Double? = null,

    
    val patientIntervention: kotlin.Double? = null,

    
    val doctorSupplement: kotlin.Double? = null,

    
    val vat: kotlin.Double? = null,

    
    val label: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */
    
    val encryptedSelf: kotlin.String? = null

)

