/**
* iCure Cloud API Documentation
* Spring shop sample application
*
* The version of the OpenAPI document: v0.0.1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.icure.kraken.client.models.decrypted

import io.icure.kraken.client.models.PaginatedDocumentKeyIdPairObject



/**
 *
 *
 * @param pageSize
 * @param totalSize
 * @param rows
 * @param nextKeyPair
 */

data class PaginatedListContactDto (


    val pageSize: kotlin.Int,


    val totalSize: kotlin.Int,


    val rows: kotlin.collections.List<ContactDto> = emptyList(),


    val nextKeyPair: PaginatedDocumentKeyIdPairObject? = null

)

