/**
 * iCure Cloud API Documentation
 *
 * Spring shop sample application
 *
 * The version of the OpenAPI document: v0.0.1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models.decrypted

import io.icure.kraken.client.models.CodeStubDto
import io.icure.kraken.client.models.DelegationDto

/**
 * This entity is a root level object. It represents a Document. It is serialized in JSON and saved in the underlying CouchDB database.
 *
 * @param id The Id of the document. We encourage using either a v4 UUID or a HL7 Id.
 * @param tags A tag is an item from a codification system that qualifies an entity as being member of a certain class, whatever the value it might have taken. If the tag qualifies the content of a field, it means that whatever the content of the field, the tag will always apply. For example, the label of a field is qualified using a tag. LOINC is a codification system typically used for tags.
 * @param codes A code is an item from a codification system that qualifies the content of this entity. SNOMED-CT, ICPC-2 or ICD-10 codifications systems can be used for codes
 * @param otherUtis Extra Uniform Type Identifiers
 * @param secretForeignKeys The secretForeignKeys are filled at the to many end of a one to many relationship (for example inside Contact for the Patient -> Contacts relationship). Used when we want to find all contacts for a specific patient. These keys are in clear. You can have several to partition the medical document space.
 * @param cryptedForeignKeys The secretForeignKeys are filled at the to many end of a one to many relationship (for example inside Contact for the Patient -> Contacts relationship). Used when we want to find the patient for a specific contact. These keys are the encrypted id (using the hcParty key for the delegate) that can be found in clear inside the patient. ids encrypted using the hcParty keys.
 * @param delegations When a document is created, the responsible generates a cryptographically random master key (never to be used for something else than referencing from other entities). He/she encrypts it using his own AES exchange key and stores it as a delegation. The responsible is thus always in the delegations as well
 * @param encryptionKeys When a document needs to be encrypted, the responsible generates a cryptographically random master key (different from the delegation key, never to appear in clear anywhere in the db. He/she encrypts it using his own AES exchange key and stores it as a delegation
 * @param rev The revision of the document in the database, used for conflict management / optimistic locking.
 * @param created The timestamp (unix epoch in ms) of creation of this entity, will be filled automatically if missing. Not enforced by the application server.
 * @param modified The date (unix epoch in ms) of the latest modification of this entity, will be filled automatically if missing. Not enforced by the application server.
 * @param author The id of the User that has created this entity, will be filled automatically if missing. Not enforced by the application server.
 * @param responsible The id of the HealthcareParty that is responsible for this entity, will be filled automatically if missing. Not enforced by the application server.
 * @param medicalLocationId The id of the medical location where this entity was created.
 * @param endOfLife Soft delete (unix epoch in ms) timestamp of the object.
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param objectStoreReference Reference in object store
 * @param documentLocation Location of the document
 * @param documentType The type of document, ex: admission, clinical path, document report,invoice, etc.
 * @param documentStatus The status of the development of the document. Ex: Draft, finalized, reviewed, signed, etc.
 * @param externalUri When the document is stored in an external repository, this is the uri of the document in that repository
 * @param mainUti The main Uniform Type Identifier of the document (https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE)
 * @param name Name of the document
 * @param version The document version
 * @param storedICureDocumentId The ICureDocument (Form, Contact, ...) that has been used to generate the document
 * @param externalUuid A unique external id (from another external source).
 * @param propertySize Size of the document file
 * @param hash Hashed version of the document
 * @param openingContactId Id of the contact during which the document was created
 * @param attachmentId Id of attachment to this document
 * @param encryptedAttachment
 * @param decryptedAttachment
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class DocumentDto (

    /* The Id of the document. We encourage using either a v4 UUID or a HL7 Id. */

    val id: kotlin.String,

    /* A tag is an item from a codification system that qualifies an entity as being member of a certain class, whatever the value it might have taken. If the tag qualifies the content of a field, it means that whatever the content of the field, the tag will always apply. For example, the label of a field is qualified using a tag. LOINC is a codification system typically used for tags. */

    val tags: kotlin.collections.List<CodeStubDto> = emptyList(),

    /* A code is an item from a codification system that qualifies the content of this entity. SNOMED-CT, ICPC-2 or ICD-10 codifications systems can be used for codes */

    val codes: kotlin.collections.List<CodeStubDto> = emptyList(),

    /* Extra Uniform Type Identifiers */

    val otherUtis: kotlin.collections.List<kotlin.String> = emptyList(),

    /* The secretForeignKeys are filled at the to many end of a one to many relationship (for example inside Contact for the Patient -> Contacts relationship). Used when we want to find all contacts for a specific patient. These keys are in clear. You can have several to partition the medical document space. */

    val secretForeignKeys: kotlin.collections.List<kotlin.String> = emptyList(),

    /* The secretForeignKeys are filled at the to many end of a one to many relationship (for example inside Contact for the Patient -> Contacts relationship). Used when we want to find the patient for a specific contact. These keys are the encrypted id (using the hcParty key for the delegate) that can be found in clear inside the patient. ids encrypted using the hcParty keys. */

    val cryptedForeignKeys: kotlin.collections.Map<kotlin.String, kotlin.collections.Set<DelegationDto>> = emptyMap(),

    /* When a document is created, the responsible generates a cryptographically random master key (never to be used for something else than referencing from other entities). He/she encrypts it using his own AES exchange key and stores it as a delegation. The responsible is thus always in the delegations as well */

    val delegations: kotlin.collections.Map<kotlin.String, kotlin.collections.Set<DelegationDto>> = emptyMap(),

    /* When a document needs to be encrypted, the responsible generates a cryptographically random master key (different from the delegation key, never to appear in clear anywhere in the db. He/she encrypts it using his own AES exchange key and stores it as a delegation */

    val encryptionKeys: kotlin.collections.Map<kotlin.String, kotlin.collections.Set<DelegationDto>> = emptyMap(),

    /* The revision of the document in the database, used for conflict management / optimistic locking. */

    val rev: kotlin.String? = null,

    /* The timestamp (unix epoch in ms) of creation of this entity, will be filled automatically if missing. Not enforced by the application server. */

    val created: kotlin.Long? = null,

    /* The date (unix epoch in ms) of the latest modification of this entity, will be filled automatically if missing. Not enforced by the application server. */

    val modified: kotlin.Long? = null,

    /* The id of the User that has created this entity, will be filled automatically if missing. Not enforced by the application server. */

    val author: kotlin.String? = null,

    /* The id of the HealthcareParty that is responsible for this entity, will be filled automatically if missing. Not enforced by the application server. */

    val responsible: kotlin.String? = null,

    /* The id of the medical location where this entity was created. */

    val medicalLocationId: kotlin.String? = null,

    /* Soft delete (unix epoch in ms) timestamp of the object. */

    val endOfLife: kotlin.Long? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,

    /* Reference in object store */

    val objectStoreReference: kotlin.String? = null,

    /* Location of the document */

    val documentLocation: DocumentDto.DocumentLocation? = null,

    /* The type of document, ex: admission, clinical path, document report,invoice, etc. */

    val documentType: DocumentDto.DocumentType? = null,

    /* The status of the development of the document. Ex: Draft, finalized, reviewed, signed, etc. */

    val documentStatus: DocumentDto.DocumentStatus? = null,

    /* When the document is stored in an external repository, this is the uri of the document in that repository */

    val externalUri: kotlin.String? = null,

    /* The main Uniform Type Identifier of the document (https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE) */

    val mainUti: kotlin.String? = null,

    /* Name of the document */

    val name: kotlin.String? = null,

    /* The document version */

    val version: kotlin.String? = null,

    /* The ICureDocument (Form, Contact, ...) that has been used to generate the document */

    val storedICureDocumentId: kotlin.String? = null,

    /* A unique external id (from another external source). */

    val externalUuid: kotlin.String? = null,

    /* Size of the document file */

    val propertySize: kotlin.Long? = null,

    /* Hashed version of the document */

    val hash: kotlin.String? = null,

    /* Id of the contact during which the document was created */

    val openingContactId: kotlin.String? = null,

    /* Id of attachment to this document */

    val attachmentId: kotlin.String? = null,


    val encryptedAttachment: ByteArray? = null,


    val decryptedAttachment: ByteArray? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */

    val encryptedSelf: kotlin.String? = null

) {

    /**
     * Location of the document
     *
     * Values: annex,body
     */
    enum class DocumentLocation(val value: kotlin.String) {
        annex("annex"),
        body("body");
    }
    /**
     * The type of document, ex: admission, clinical path, document report,invoice, etc.
     *
     * Values: admission,alert,bvtSample,clinicalpath,clinicalsummary,contactreport,quote,invoice,death,discharge,dischargereport,ebirthBabyMedicalform,ebirthBabyNotification,ebirthMotherMedicalform,ebirthMotherNotification,ecareSafeConsultation,epidemiology,intervention,labrequest,labresult,medicaladvisoragreement,medicationschemeelement,note,notification,pharmaceuticalprescription,prescription,productdelivery,quickdischargereport,radiationexposuremonitoring,referral,report,request,result,sumehr,telemonitoring,template,templateAdmin,treatmentsuspension,vaccination
     */
    enum class DocumentType(val value: kotlin.String) {
        admission("admission"),
        alert("alert"),
        bvtSample("bvt_sample"),
        clinicalpath("clinicalpath"),
        clinicalsummary("clinicalsummary"),
        contactreport("contactreport"),
        quote("quote"),
        invoice("invoice"),
        death("death"),
        discharge("discharge"),
        dischargereport("dischargereport"),
        ebirthBabyMedicalform("ebirth_baby_medicalform"),
        ebirthBabyNotification("ebirth_baby_notification"),
        ebirthMotherMedicalform("ebirth_mother_medicalform"),
        ebirthMotherNotification("ebirth_mother_notification"),
        ecareSafeConsultation("ecare_safe_consultation"),
        epidemiology("epidemiology"),
        intervention("intervention"),
        labrequest("labrequest"),
        labresult("labresult"),
        medicaladvisoragreement("medicaladvisoragreement"),
        medicationschemeelement("medicationschemeelement"),
        note("note"),
        notification("notification"),
        pharmaceuticalprescription("pharmaceuticalprescription"),
        prescription("prescription"),
        productdelivery("productdelivery"),
        quickdischargereport("quickdischargereport"),
        radiationexposuremonitoring("radiationexposuremonitoring"),
        referral("referral"),
        report("report"),
        request("request"),
        result("result"),
        sumehr("sumehr"),
        telemonitoring("telemonitoring"),
        template("template"),
        templateAdmin("template_admin"),
        treatmentsuspension("treatmentsuspension"),
        vaccination("vaccination");
    }
    /**
     * The status of the development of the document. Ex: Draft, finalized, reviewed, signed, etc.
     *
     * Values: draft,finalized,pendingReview,reviewed,pendingSignature,signed,canceled,sent,delivered
     */
    enum class DocumentStatus(val value: kotlin.String) {
        draft("draft"),
        finalized("finalized"),
        pendingReview("pending_review"),
        reviewed("reviewed"),
        pendingSignature("pending_signature"),
        signed("signed"),
        canceled("canceled"),
        sent("sent"),
        delivered("delivered");
    }
}

