/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models.decrypted

import io.icure.kraken.client.models.PaginatedDocumentKeyIdPairObject


/**
 *
 *
 * @param pageSize
 * @param totalSize
 * @param rows
 * @param nextKeyPair
 */

data class PaginatedListHealthElementDto(

    
    val pageSize: Int,

    
    val totalSize: Int,

    
    val rows: List<HealthElementDto> = emptyList(),

    
    val nextKeyPair: PaginatedDocumentKeyIdPairObject? = null

)

