/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param verseSeq
 * @param documentSeq
 * @param from
 * @param to
 * @param mimeType
 * @param addressUrl
 * @param descrNl
 * @param descrFr
 * @param localPath
 */

data class AddedDocumentDto (


    val verseSeq: kotlin.Long,


    val documentSeq: kotlin.Long,


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val mimeType: kotlin.String? = null,


    val addressUrl: kotlin.String? = null,


    val descrNl: kotlin.String? = null,


    val descrFr: kotlin.String? = null,


    val localPath: kotlin.String? = null

)

