/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param from
 * @param to
 * @param ingredients
 * @param pharmaceuticalForms
 * @param routeOfAdministrations
 * @param dividable
 * @param scored
 * @param crushable
 * @param containsAlcohol
 * @param sugarFree
 * @param modifiedReleaseType
 * @param specificDrugDevice
 * @param dimensions
 * @param name
 * @param note
 */

data class AmpComponentDto (


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val ingredients: kotlin.collections.List<IngredientDto>? = null,


    val pharmaceuticalForms: kotlin.collections.List<PharmaceuticalFormStubDto>? = null,


    val routeOfAdministrations: kotlin.collections.List<RouteOfAdministrationDto>? = null,


    val dividable: kotlin.String? = null,


    val scored: kotlin.String? = null,


    val crushable: AmpComponentDto.Crushable? = null,


    val containsAlcohol: AmpComponentDto.ContainsAlcohol? = null,


    val sugarFree: kotlin.Boolean? = null,


    val modifiedReleaseType: kotlin.Int? = null,


    val specificDrugDevice: kotlin.Int? = null,


    val dimensions: kotlin.String? = null,


    val name: SamTextDto? = null,


    val note: SamTextDto? = null

) {

    /**
     *
     *
     * Values: y,n,x
     */
    enum class Crushable(val value: kotlin.String) {
        y("Y"),
        n("N"),
        x("X");
    }
    /**
     *
     *
     * Values: y,n,x
     */
    enum class ContainsAlcohol(val value: kotlin.String) {
        y("Y"),
        n("N"),
        x("X");
    }
}

