/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param calendarItemTypeId
 * @param duration
 * @param acceptsNewPatients
 * @param name
 * @param color
 * @param subjectByLanguage
 * @param placeId
 * @param address
 */

data class AppointmentTypeAndPlaceDto (


    val calendarItemTypeId: kotlin.String,


    val duration: kotlin.Int = 0,


    val acceptsNewPatients: kotlin.Boolean,


    val name: kotlin.String? = null,


    val color: kotlin.String? = null,


    val subjectByLanguage: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,


    val placeId: kotlin.String? = null,


    val address: AddressDto? = null

)

