/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param code 
 * @param date 
 * @param userId 
 * @param userName 
 */

data class CalendarItemTagDto (

    
    val code: kotlin.String? = null,

    
    val date: kotlin.Long? = null,

    
    val userId: kotlin.String? = null,

    
    val userName: kotlin.String? = null

)

