/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * Members of the careteam involved in this approach
 *
 * @param startDate
 * @param endDate
 * @param careTeamMemberId
 * @param membershipType
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class CareTeamMembershipDto (


    val startDate: kotlin.Long? = null,


    val endDate: kotlin.Long? = null,


    val careTeamMemberId: kotlin.String? = null,


    val membershipType: CareTeamMembershipDto.MembershipType? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */

    val encryptedSelf: kotlin.String? = null

) {

    /**
     *
     *
     * Values: doctor,mutuality,patient,specialist,other
     */
    enum class MembershipType(val value: kotlin.String) {
        doctor("doctor"),
        mutuality("mutuality"),
        patient("patient"),
        specialist("specialist"),
        other("other");
    }
}

