/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param from
 * @param to
 * @param reason
 * @param endOfComercialization
 * @param impact
 * @param additionalInformation
 */

data class CommercializationDto (


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val reason: SamTextDto? = null,


    val endOfComercialization: SamTextDto? = null,


    val impact: SamTextDto? = null,


    val additionalInformation: SamTextDto? = null

)

