/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param source 
 * @param target 
 * @param filter 
 * @param localTarget 
 */

data class DatabaseSynchronizationDto (

    
    val source: kotlin.String? = null,

    
    val target: kotlin.String? = null,

    
    val filter: kotlin.String? = null,

    
    val localTarget: DatabaseSynchronizationDto.LocalTarget? = null

) {

    /**
     * 
     *
     * Values: base,healthdata,patient
     */
    enum class LocalTarget(val value: kotlin.String) {
        base("base"),
        healthdata("healthdata"),
        patient("patient");
    }
}

