/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param items
 * @param ignorePrescriptionDate
 * @param hospitalisedPatient
 * @param creditNote
 * @param patient
 * @param ioCode
 * @param reason
 * @param invoiceRef
 * @param invoiceNumber
 * @param relatedInvoiceIoCode
 * @param relatedInvoiceNumber
 * @param relatedBatchSendNumber
 * @param relatedBatchYearMonth
 */

data class EfactInvoice (


    val items: kotlin.collections.List<InvoiceItem> = emptyList(),


    val ignorePrescriptionDate: kotlin.Boolean,


    val hospitalisedPatient: kotlin.Boolean,


    val creditNote: kotlin.Boolean,


    val patient: PatientDto? = null,


    val ioCode: kotlin.String? = null,


    val reason: EfactInvoice.Reason? = null,


    val invoiceRef: kotlin.String? = null,


    val invoiceNumber: kotlin.Long? = null,


    val relatedInvoiceIoCode: kotlin.String? = null,


    val relatedInvoiceNumber: kotlin.Long? = null,


    val relatedBatchSendNumber: kotlin.Long? = null,


    val relatedBatchYearMonth: kotlin.Long? = null

) {

    /**
     *
     *
     * Values: chimiotherapy,professionalDisease,workAccident,accident,other
     */
    enum class Reason(val value: kotlin.String) {
        chimiotherapy("Chimiotherapy"),
        professionalDisease("ProfessionalDisease"),
        workAccident("WorkAccident"),
        accident("Accident"),
        other("Other");
    }
}

