/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param readHour 
 * @param deviceType 
 * @param readDate 
 * @param readType 
 * @param readvalue 
 */

data class EIDItem (

    
    val readHour: kotlin.Int = 0,

    
    val deviceType: kotlin.String? = null,

    
    val readDate: kotlin.Long? = null,

    
    val readType: kotlin.String? = null,

    
    val readvalue: kotlin.String? = null

)

