/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param `value`
 * @param lifecycle
 */

data class Formula (


    val `value`: kotlin.String? = null,


    val lifecycle: Formula.Lifecycle? = null

) {

    /**
     *
     *
     * Values: onCreate,onLoad,onChange,onSave,onDestroy,onLoadPropertiesEditor
     */
    enum class Lifecycle(val value: kotlin.String) {
        onCreate("OnCreate"),
        onLoad("OnLoad"),
        onChange("OnChange"),
        onSave("OnSave"),
        onDestroy("OnDestroy"),
        onLoadPropertiesEditor("OnLoadPropertiesEditor");
    }
}

