/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param subForm
 * @param irrelevant
 * @param determinesSscontactName
 * @param type
 * @param name
 * @param sortOrder
 * @param options
 * @param descr
 * @param label
 * @param editor
 * @param defaultValue
 * @param defaultStatus
 * @param suggest
 * @param plannings
 * @param tags
 * @param codes
 * @param codeTypes
 * @param formulas
 */

data class FormLayoutData (


    val subForm: kotlin.Boolean? = null,


    val irrelevant: kotlin.Boolean? = null,


    val determinesSscontactName: kotlin.Boolean? = null,


    val type: kotlin.String? = null,


    val name: kotlin.String? = null,


    val sortOrder: kotlin.Double? = null,


    val options: kotlin.collections.Map<kotlin.String, FormDataOption>? = null,


    val descr: kotlin.String? = null,


    val label: kotlin.String? = null,


    val editor: Editor? = null,


    val defaultValue: kotlin.collections.List<ContentDto>? = null,


    val defaultStatus: kotlin.Int? = null,


    val suggest: kotlin.collections.List<Suggest>? = null,


    val plannings: kotlin.collections.List<FormPlanning>? = null,


    val tags: kotlin.collections.List<GuiCode>? = null,


    val codes: kotlin.collections.List<GuiCode>? = null,


    val codeTypes: kotlin.collections.List<GuiCodeType>? = null,


    val formulas: kotlin.collections.List<Formula>? = null

)

