/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param formDataList
 * @param columns
 * @param shouldDisplay
 */

data class FormColumn (


    val formDataList: kotlin.collections.List<FormLayoutData>? = null,


    val columns: kotlin.String? = null,


    val shouldDisplay: kotlin.Boolean? = null

)

