/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * This entity represents a group
 *
 * @param id The id of the group. We encourage using either a v4 UUID or a HL7 Id.
 * @param superAdmin Whether the group has a super admin permission, originally set to no access.
 * @param properties Extra properties for the user. Those properties are typed (see class Property)
 * @param rev The revision of the group in the database, used for conflict management / optimistic locking.
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param name Username for the group
 * @param password Password for the group access
 * @param servers List of servers accessible to the group
 * @param superGroup
 */

data class GroupDto (

    /* The id of the group. We encourage using either a v4 UUID or a HL7 Id. */

    val id: kotlin.String,

    /* Whether the group has a super admin permission, originally set to no access. */

    val superAdmin: kotlin.Boolean,

    /* Extra properties for the user. Those properties are typed (see class Property) */

    val properties: kotlin.collections.List<PropertyStubDto> = emptyList(),

    /* The revision of the group in the database, used for conflict management / optimistic locking. */

    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,

    /* Username for the group */

    val name: kotlin.String? = null,

    /* Password for the group access */

    val password: kotlin.String? = null,

    /* List of servers accessible to the group */

    val servers: kotlin.collections.List<kotlin.String>? = null,


    val superGroup: kotlin.String? = null

)

