/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * The healthcare party's status history
 *
 * @param status
 * @param specialisationCode
 * @param startDate
 * @param active
 */

data class HealthcarePartyHistoryStatusDto (

    
    val status: HealthcarePartyHistoryStatusDto.Status,

    
    val specialisationCode: kotlin.String,

    
    val startDate: kotlin.Long,

    
    val active: kotlin.Boolean

) {

    /**
     *
     *
     * Values: trainee,withconvention,accreditated
     */
    enum class Status(val value: kotlin.String) {
        trainee("trainee"),
        withconvention("withconvention"),
        accreditated("accreditated");
    }
}

