/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param eidDocumentSupportType
 * @param reasonManualEncoding
 * @param reasonUsingVignette
 * @param justificatifDocumentNumber
 * @param supportSerialNumber
 * @param timeReadingEIdDocument
 */

data class IdentityDocumentReaderDto (


    val eidDocumentSupportType: kotlin.Int = 0,


    val reasonManualEncoding: kotlin.Int = 0,


    val reasonUsingVignette: kotlin.Int = 0,


    val justificatifDocumentNumber: kotlin.String? = null,


    val supportSerialNumber: kotlin.String? = null,


    val timeReadingEIdDocument: kotlin.Long? = null

)

