/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param id
 * @param assigner
 * @param start
 * @param end
 * @param system
 * @param type
 * @param use
 * @param `value`
 */

data class IdentifierDto (


    val id: kotlin.String? = null,


    val assigner: kotlin.String? = null,


    val start: kotlin.String? = null,


    val end: kotlin.String? = null,


    val system: kotlin.String? = null,


    val type: CodeStubDto? = null,


    val use: kotlin.String? = null,


    val `value`: kotlin.String? = null

)

