/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param patient
 * @param hes
 * @param ctcs
 * @param warnings
 * @param errors
 * @param forms
 * @param hcps
 * @param documents
 * @param attachments
 */

data class ImportResultDto (


    val patient: PatientDto? = null,


    val hes: kotlin.collections.List<HealthElementDto>? = null,


    val ctcs: kotlin.collections.List<ContactDto>? = null,


    val warnings: kotlin.collections.List<kotlin.String>? = null,


    val errors: kotlin.collections.List<kotlin.String>? = null,


    val forms: kotlin.collections.List<FormDto>? = null,


    val hcps: kotlin.collections.List<HealthcarePartyDto>? = null,


    val documents: kotlin.collections.List<DocumentDto>? = null,


    val attachments: kotlin.collections.Map<kotlin.String, MimeAttachmentDto>? = null

)

