/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param direct 
 * @param char 
 * @param short 
 * @param int 
 * @param long 
 * @param float 
 * @param double 
 * @param readOnly 
 */

data class InlineResponse200 (

    
    val direct: kotlin.Boolean? = null,

    
    val char: kotlin.String? = null,

    
    val short: kotlin.Int? = null,

    
    val int: kotlin.Int? = null,

    
    val long: kotlin.Long? = null,

    
    val float: kotlin.Float? = null,

    
    val double: kotlin.Double? = null,

    
    val readOnly: kotlin.Boolean? = null

)

