/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param isSpecialist
 * @param nihii
 * @param bic
 * @param iban
 * @param bce
 * @param ssin
 * @param lastName
 * @param firstName
 * @param phoneNumber
 * @param conventionCode
 */

data class InvoiceSender (


    val isSpecialist: kotlin.Boolean = false,


    val nihii: kotlin.Long? = null,


    val bic: kotlin.String? = null,


    val iban: kotlin.String? = null,


    val bce: kotlin.Long? = null,


    val ssin: kotlin.String? = null,


    val lastName: kotlin.String? = null,


    val firstName: kotlin.String? = null,


    val phoneNumber: kotlin.Long? = null,


    val conventionCode: kotlin.Int? = null

)

