/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param letter
 * @param index
 * @param coefficient
 * @param `value`
 */

data class LetterValueDto (


    val letter: kotlin.String? = null,


    val index: kotlin.String? = null,


    val coefficient: kotlin.Double? = null,


    val `value`: kotlin.Double? = null

)

