/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param id
 * @param agendaIds
 * @param options
 * @param rev
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param name
 * @param description
 * @param responsible
 * @param guardPost
 * @param cbe
 * @param bic
 * @param bankAccount
 * @param nihii
 * @param ssin
 * @param address
 */

data class MedicalLocationDto (


    val id: kotlin.String,


    val agendaIds: kotlin.collections.List<kotlin.String> = emptyList(),


    val options: kotlin.collections.Map<kotlin.String, kotlin.String> = emptyMap(),


    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,


    val name: kotlin.String? = null,


    val description: kotlin.String? = null,


    val responsible: kotlin.String? = null,


    val guardPost: kotlin.Boolean? = null,


    val cbe: kotlin.String? = null,


    val bic: kotlin.String? = null,


    val bankAccount: kotlin.String? = null,


    val nihii: kotlin.String? = null,


    val ssin: kotlin.String? = null,


    val address: AddressDto? = null

)

