/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * Status showing whether the message is read or not and the time of reading
 *
 * @param read
 * @param time
 */

data class MessageReadStatusDto (


    val read: kotlin.Boolean = false,


    val time: kotlin.Long? = null

)

