/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param min
 * @param max
 * @param unit
 */

data class NumeratorRangeDto (

    
    val min: java.math.BigDecimal? = null,

    
    val max: java.math.BigDecimal? = null,

    
    val unit: kotlin.String? = null

)

