/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param timestamp
 * @param paragraph
 * @param accepted
 * @param inTreatment
 * @param canceled
 * @param careProviderReference
 * @param decisionReference
 * @param start
 * @param end
 * @param cancelationDate
 * @param quantityValue
 * @param quantityUnit
 * @param ioRequestReference
 * @param responseType
 * @param refusalJustification
 * @param verses
 * @param coverageType
 * @param unitNumber
 * @param strength
 * @param strengthUnit
 * @param agreementAppendices
 * @param documentId
 */

data class ParagraphAgreementDto (


    val timestamp: kotlin.Long? = null,


    val paragraph: kotlin.String? = null,


    val accepted: kotlin.Boolean? = null,


    val inTreatment: kotlin.Boolean? = null,


    val canceled: kotlin.Boolean? = null,


    val careProviderReference: kotlin.String? = null,


    val decisionReference: kotlin.String? = null,


    val start: kotlin.Long? = null,


    val end: kotlin.Long? = null,


    val cancelationDate: kotlin.Long? = null,


    val quantityValue: kotlin.Double? = null,


    val quantityUnit: kotlin.String? = null,


    val ioRequestReference: kotlin.String? = null,


    val responseType: kotlin.String? = null,


    val refusalJustification: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,


    val verses: kotlin.collections.Set<kotlin.Long>? = null,


    val coverageType: kotlin.String? = null,


    val unitNumber: kotlin.Double? = null,


    val strength: kotlin.Double? = null,


    val strengthUnit: kotlin.String? = null,


    val agreementAppendices: kotlin.collections.List<AgreementAppendixDto>? = null,


    val documentId: kotlin.String? = null

)

