/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * Revoked permissions.
 *
 * @param type
 * @param predicate
 */

data class PermissionItemDto (


    val type: PermissionItemDto.Type,


    val predicate: kotlin.Any

) {

    /**
     *
     *
     * Values: aUTHENTICATE,aDMIN,pATIENTVIEW,pATIENTCREATE,pATIENTCHANGEDELETE,mEDICALDATAVIEW,mEDICALDATACREATE,mEDICALCHANGEDELETE,fINANCIALDATAVIEW,fINANCIALDATACREATE,fINANCIALCHANGEDELETE
     */
    enum class Type(val value: kotlin.String) {
        aUTHENTICATE("AUTHENTICATE"),
        aDMIN("ADMIN"),
        pATIENTVIEW("PATIENT_VIEW"),
        pATIENTCREATE("PATIENT_CREATE"),
        pATIENTCHANGEDELETE("PATIENT_CHANGE_DELETE"),
        mEDICALDATAVIEW("MEDICAL_DATA_VIEW"),
        mEDICALDATACREATE("MEDICAL_DATA_CREATE"),
        mEDICALCHANGEDELETE("MEDICAL_CHANGE_DELETE"),
        fINANCIALDATAVIEW("FINANCIAL_DATA_VIEW"),
        fINANCIALDATACREATE("FINANCIAL_DATA_CREATE"),
        fINANCIALCHANGEDELETE("FINANCIAL_CHANGE_DELETE");
    }
}

