/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param from
 * @param to
 * @param deliveryEnvironment
 * @param code
 * @param codeType
 * @param multiple
 * @param temporary
 * @param reference
 * @param legalReferencePath
 * @param flatRateSystem
 * @param reimbursementBasePrice
 * @param referenceBasePrice
 * @param copaymentSupplement
 * @param pricingUnit
 * @param pricingSlice
 * @param reimbursementCriterion
 * @param copayments
 */

data class ReimbursementDto (


    val from: kotlin.Long? = null,


    val to: kotlin.Long? = null,


    val deliveryEnvironment: ReimbursementDto.DeliveryEnvironment? = null,


    val code: kotlin.String? = null,


    val codeType: ReimbursementDto.CodeType? = null,


    val multiple: ReimbursementDto.Multiple? = null,


    val temporary: kotlin.Boolean? = null,


    val reference: kotlin.Boolean? = null,


    val legalReferencePath: kotlin.String? = null,


    val flatRateSystem: kotlin.Boolean? = null,


    val reimbursementBasePrice: java.math.BigDecimal? = null,


    val referenceBasePrice: java.math.BigDecimal? = null,


    val copaymentSupplement: java.math.BigDecimal? = null,


    val pricingUnit: PricingDto? = null,


    val pricingSlice: PricingDto? = null,


    val reimbursementCriterion: ReimbursementCriterionDto? = null,


    val copayments: kotlin.collections.List<CopaymentDto>? = null

) {

    /**
     *
     *
     * Values: p,a,h,r
     */
    enum class DeliveryEnvironment(val value: kotlin.String) {
        p("P"),
        a("A"),
        h("H"),
        r("R");
    }
    /**
     *
     *
     * Values: cNK,pSEUDO
     */
    enum class CodeType(val value: kotlin.String) {
        cNK("CNK"),
        pSEUDO("PSEUDO");
    }
    /**
     *
     *
     * Values: m,v
     */
    enum class Multiple(val value: kotlin.String) {
        m("M"),
        v("V");
    }
}

