/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param language
 * @param script
 * @param country
 * @param variant
 * @param extensionKeys
 * @param unicodeLocaleAttributes
 * @param unicodeLocaleKeys
 * @param iso3Language
 * @param iso3Country
 * @param displayLanguage
 * @param displayScript
 * @param displayCountry
 * @param displayVariant
 * @param displayName
 */

data class RestV2BeSamv2ChapChapterNameParagraphNameVerseSeqAddeddocDocSeqLanguageLocale (


    val language: kotlin.String? = null,


    val script: kotlin.String? = null,


    val country: kotlin.String? = null,


    val variant: kotlin.String? = null,


    val extensionKeys: kotlin.collections.Set<kotlin.String>? = null,


    val unicodeLocaleAttributes: kotlin.collections.Set<kotlin.String>? = null,


    val unicodeLocaleKeys: kotlin.collections.Set<kotlin.String>? = null,


    val iso3Language: kotlin.String? = null,


    val iso3Country: kotlin.String? = null,


    val displayLanguage: kotlin.String? = null,


    val displayScript: kotlin.String? = null,


    val displayCountry: kotlin.String? = null,


    val displayVariant: kotlin.String? = null,


    val displayName: kotlin.String? = null

)

