/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param codes
 * @param services
 * @param ssin
 * @param lastName
 * @param firstName
 * @param dateOfBirth
 * @param sex
 * @param documentId
 * @param protocol
 * @param complete
 * @param demandDate
 * @param labo
 * @param engine
 */

data class ResultInfoDto (


    val codes: kotlin.collections.List<CodeStubDto> = emptyList(),


    val services: kotlin.collections.List<ServiceDto> = emptyList(),


    val ssin: kotlin.String? = null,


    val lastName: kotlin.String? = null,


    val firstName: kotlin.String? = null,


    val dateOfBirth: kotlin.Long? = null,


    val sex: kotlin.String? = null,


    val documentId: kotlin.String? = null,


    val protocol: kotlin.String? = null,


    val complete: kotlin.Boolean? = null,


    val demandDate: kotlin.Long? = null,


    val labo: kotlin.String? = null,


    val engine: kotlin.String? = null

)

