/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param fr
 * @param nl
 * @param de
 * @param en
 */

data class SamTextDto (


    val fr: kotlin.String? = null,


    val nl: kotlin.String? = null,


    val de: kotlin.String? = null,


    val en: kotlin.String? = null

)

