/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param startDate
 * @param endDate
 * @param school
 * @param typeOfEducation
 */

data class SchoolingInfoDto (


    val startDate: kotlin.Long? = null,


    val endDate: kotlin.Long? = null,


    val school: kotlin.String? = null,


    val typeOfEducation: CodeStubDto? = null

)

