/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * 
 *
 * @param secretForeignKeys 
 * @param exportAsPMF 
 * @param comment 
 * @param softwareName 
 * @param softwareVersion 
 */

data class SoftwareMedicalFileExportDto (

    
    val secretForeignKeys: kotlin.collections.List<kotlin.String> = emptyList(),

    
    val exportAsPMF: kotlin.Boolean,

    
    val comment: kotlin.String? = null,

    
    val softwareName: kotlin.String? = null,

    
    val softwareVersion: kotlin.String? = null

)

