/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * 
 *
 * @param code 
 * @param type 
 * @param name 
 * @param definition 
 * @param url 
 */

data class StandardSubstanceDto (

    
    val code: kotlin.String? = null,

    
    val type: StandardSubstanceDto.Type? = null,

    
    val name: SamTextDto? = null,

    
    val definition: SamTextDto? = null,

    
    val url: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: cAS,dMD,eDQM,sNOMEDCT
     */
    enum class Type(val value: kotlin.String) {
        cAS("CAS"),
        dMD("DM_D"),
        eDQM("EDQM"),
        sNOMEDCT("SNOMED_CT");
    }
}

