/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param secretForeignKeys
 * @param excludedIds
 * @param comment
 * @param recipient
 * @param softwareName
 * @param softwareVersion
 * @param includeIrrelevantInformation
 * @param services
 * @param healthElements
 */

data class SumehrExportInfoDto (


    val secretForeignKeys: kotlin.collections.List<kotlin.String> = emptyList(),


    val excludedIds: kotlin.collections.List<kotlin.String> = emptyList(),


    val comment: kotlin.String = "",


    val recipient: HealthcarePartyDto? = null,


    val softwareName: kotlin.String? = null,


    val softwareVersion: kotlin.String? = null,


    val includeIrrelevantInformation: kotlin.Boolean? = null,


    val services: kotlin.collections.List<ServiceDto>? = null,


    val healthElements: kotlin.collections.List<HealthElementDto>? = null

)

