/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param beginMoment
 * @param endMoment
 * @param suspensionReason
 * @param lifecycle
 */

data class SuspensionDto (


    val beginMoment: kotlin.Long? = null,


    val endMoment: kotlin.Long? = null,


    val suspensionReason: kotlin.String? = null,


    val lifecycle: kotlin.String? = null

)

