/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 * This entity represents available contact details of a user, reachable by telecom methods
 *
 * @param telecomType The type of telecom method being used, ex: landline phone, mobile phone, email, fax, etc.
 * @param telecomNumber
 * @param telecomDescription
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class TelecomDto (

    /* The type of telecom method being used, ex: landline phone, mobile phone, email, fax, etc. */

    val telecomType: TelecomDto.TelecomType? = null,


    val telecomNumber: kotlin.String? = null,


    val telecomDescription: kotlin.String? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */

    val encryptedSelf: kotlin.String? = null

) {

    /**
     * The type of telecom method being used, ex: landline phone, mobile phone, email, fax, etc.
     *
     * Values: mobile,phone,email,fax,skype,im,medibridge,ehealthbox,apicrypt,web,print,disk,other,pager
     */
    enum class TelecomType(val value: kotlin.String) {
        mobile("mobile"),
        phone("phone"),
        email("email"),
        fax("fax"),
        skype("skype"),
        im("im"),
        medibridge("medibridge"),
        ehealthbox("ehealthbox"),
        apicrypt("apicrypt"),
        web("web"),
        print("print"),
        disk("disk"),
        other("other"),
        pager("pager");
    }
}

