/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param type
 * @param booleanValue
 * @param integerValue
 * @param doubleValue
 * @param stringValue
 * @param dateValue
 * @param encryptedSelf The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys.
 */

data class TypedValueDtoObject (


    val type: TypedValueDtoObject.Type? = null,


    val booleanValue: kotlin.Boolean? = null,


    val integerValue: kotlin.Int? = null,


    val doubleValue: kotlin.Double? = null,


    val stringValue: kotlin.String? = null,


    val dateValue: java.time.OffsetDateTime? = null,

    /* The base64 encoded data of this object, formatted as JSON and encrypted in AES using the random master key from encryptionKeys. */

    val encryptedSelf: kotlin.String? = null

) {

    /**
     *
     *
     * Values: bOOLEAN,iNTEGER,dOUBLE,sTRING,dATE,cLOB,jSON
     */
    enum class Type(val value: kotlin.String) {
        bOOLEAN("BOOLEAN"),
        iNTEGER("INTEGER"),
        dOUBLE("DOUBLE"),
        sTRING("STRING"),
        dATE("DATE"),
        cLOB("CLOB"),
        jSON("JSON");
    }
}

