/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * This entity embeds a User and its linked Healthcare Party.
 *
 * @param user
 * @param healthcareParty
 */

data class UserAndHealthcarePartyDto (


    val user: UserDto,


    val healthcareParty: HealthcarePartyDto

)

