/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models




/**
 *
 *
 * @param groupId
 * @param userId
 * @param groupName
 */

data class UserGroupDto (


    val groupId: kotlin.String? = null,


    val userId: kotlin.String? = null,


    val groupName: kotlin.String? = null

)

