/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 * This entity is a root level object. It represents an user that can log in to the iCure platform. It is serialized in JSON and saved in the underlying icure-base CouchDB database.
 *
 * @param id the Id of the user. We encourage using either a v4 UUID or a HL7 Id.
 * @param properties Extra properties for the user. Those properties are typed (see class Property)
 * @param permissions If permission to modify patient data is granted or revoked
 * @param roles Roles specified for the user
 * @param autoDelegations Delegations that are automatically generated client side when a new database object is created by this user
 * @param applicationTokens
 * @param authenticationTokens Encrypted and time-limited Authentication tokens used for inter-applications authentication
 * @param rev the revision of the user in the database, used for conflict management / optimistic locking.
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param created
 * @param name Last name of the user. This is the official last name that should be used for official administrative purposes.
 * @param type Authorization source for user. 'Database', 'ldap' or 'token'
 * @param status State of user's activeness: 'Active', 'Disabled' or 'Registering'
 * @param login Username for this user. We encourage using an email address
 * @param passwordHash Hashed version of the password (BCrypt is used for hashing)
 * @param secret Secret token used to verify 2fa
 * @param use2fa Whether the user has activated two factors authentication
 * @param groupId id of the group (practice/hospital) the user is member of
 * @param healthcarePartyId Id of the healthcare party if the user is a healthcare party.
 * @param patientId Id of the patient if the user is a patient
 * @param deviceId Id of the device if the user is a device
 * @param createdDate the timestamp (unix epoch in ms) of creation of the user, will be filled automatically if missing. Not enforced by the application server.
 * @param termsOfUseDate the timestamp (unix epoch in ms) of the latest validation of the terms of use of the application
 * @param email email address of the user (used for token exchange or password recovery).
 * @param mobilePhone mobile phone of the user (used for token exchange or password recovery).
 */

data class UserDto (

    /* the Id of the user. We encourage using either a v4 UUID or a HL7 Id. */

    val id: kotlin.String,

    /* Extra properties for the user. Those properties are typed (see class Property) */

    val properties: kotlin.collections.List<PropertyStubDto> = emptyList(),

    /* If permission to modify patient data is granted or revoked */

    val permissions: kotlin.collections.List<PermissionDto> = emptyList(),

    /* Roles specified for the user */

    val roles: kotlin.collections.List<kotlin.String> = emptyList(),

    /* Delegations that are automatically generated client side when a new database object is created by this user */

    val autoDelegations: kotlin.collections.Map<kotlin.String, kotlin.collections.Set<kotlin.String>> = emptyMap(),


    @Deprecated(message = "This property is deprecated.")
    val applicationTokens: kotlin.collections.Map<kotlin.String, kotlin.String> = emptyMap(),

    /* Encrypted and time-limited Authentication tokens used for inter-applications authentication */

    val authenticationTokens: kotlin.collections.Map<kotlin.String, AuthenticationTokenDto> = emptyMap(),

    /* the revision of the user in the database, used for conflict management / optimistic locking. */

    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,


    val created: kotlin.Long? = null,

    /* Last name of the user. This is the official last name that should be used for official administrative purposes. */

    val name: kotlin.String? = null,

    /* Authorization source for user. 'Database', 'ldap' or 'token' */

    val type: UserDto.Type? = null,

    /* State of user's activeness: 'Active', 'Disabled' or 'Registering' */

    val status: UserDto.Status? = null,

    /* Username for this user. We encourage using an email address */

    val login: kotlin.String? = null,

    /* Hashed version of the password (BCrypt is used for hashing) */

    val passwordHash: kotlin.String? = null,

    /* Secret token used to verify 2fa */

    val secret: kotlin.String? = null,

    /* Whether the user has activated two factors authentication */

    val use2fa: kotlin.Boolean? = null,

    /* id of the group (practice/hospital) the user is member of */

    val groupId: kotlin.String? = null,

    /* Id of the healthcare party if the user is a healthcare party. */

    val healthcarePartyId: kotlin.String? = null,

    /* Id of the patient if the user is a patient */

    val patientId: kotlin.String? = null,

    /* Id of the device if the user is a device */

    val deviceId: kotlin.String? = null,

    /* the timestamp (unix epoch in ms) of creation of the user, will be filled automatically if missing. Not enforced by the application server. */

    val createdDate: java.time.OffsetDateTime? = null,

    /* the timestamp (unix epoch in ms) of the latest validation of the terms of use of the application */

    val termsOfUseDate: java.time.OffsetDateTime? = null,

    /* email address of the user (used for token exchange or password recovery). */

    val email: kotlin.String? = null,

    /* mobile phone of the user (used for token exchange or password recovery). */

    val mobilePhone: kotlin.String? = null

) {

    /**
     * Authorization source for user. 'Database', 'ldap' or 'token'
     *
     * Values: database,ldap,token
     */
    enum class Type(val value: kotlin.String) {
        database("database"),
        ldap("ldap"),
        token("token");
    }
    /**
     * State of user's activeness: 'Active', 'Disabled' or 'Registering'
     *
     * Values: aCTIVE,dISABLED,rEGISTERING
     */
    enum class Status(val value: kotlin.String) {
        aCTIVE("ACTIVE"),
        dISABLED("DISABLED"),
        rEGISTERING("REGISTERING");
    }
}

