/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param id
 * @param addedDocuments
 * @param rev
 * @param deletionDate hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
 * @param chapterName
 * @param paragraphName
 * @param verseSeq
 * @param startDate
 * @param createdTms
 * @param createdUserId
 * @param endDate
 * @param verseNum
 * @param verseSeqParent
 * @param verseLevel
 * @param verseType
 * @param checkBoxInd
 * @param minCheckNum
 * @param andClauseNum
 * @param textFr
 * @param textNl
 * @param requestType
 * @param agreementTerm
 * @param agreementTermUnit
 * @param maxPackageNumber
 * @param purchasingAdvisorQualList
 * @param legalReference
 * @param modificationDate
 * @param agreementYearMax
 * @param agreementRenewalMax
 * @param sexRestricted
 * @param minimumAgeAuthorized
 * @param maximumAgeAuthorized
 * @param maximumContentQuantity
 * @param maximumContentUnit
 * @param maximumStrengthQuantity
 * @param maximumStrengthUnit
 * @param maximumDurationQuantity
 * @param maximumDurationUnit
 * @param otherAddedDocumentInd
 * @param minimumAgeAuthorizedUnit
 * @param maximumAgeAuthorizedUnit
 * @param modificationStatus
 * @param children
 */

data class VerseDto (


    val id: kotlin.String,


    val addedDocuments: kotlin.collections.List<AddedDocumentDto> = emptyList(),


    val rev: kotlin.String? = null,

    /* hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called. */

    val deletionDate: kotlin.Long? = null,


    val chapterName: kotlin.String? = null,


    val paragraphName: kotlin.String? = null,


    val verseSeq: kotlin.Long? = null,


    val startDate: kotlin.Long? = null,


    val createdTms: kotlin.Long? = null,


    val createdUserId: kotlin.String? = null,


    val endDate: kotlin.Long? = null,


    val verseNum: kotlin.Long? = null,


    val verseSeqParent: kotlin.Long? = null,


    val verseLevel: kotlin.Long? = null,


    val verseType: kotlin.String? = null,


    val checkBoxInd: kotlin.String? = null,


    val minCheckNum: kotlin.Long? = null,


    val andClauseNum: kotlin.Long? = null,


    val textFr: kotlin.String? = null,


    val textNl: kotlin.String? = null,


    val requestType: kotlin.String? = null,


    val agreementTerm: kotlin.Long? = null,


    val agreementTermUnit: kotlin.String? = null,


    val maxPackageNumber: kotlin.Long? = null,


    val purchasingAdvisorQualList: kotlin.String? = null,


    val legalReference: kotlin.String? = null,


    val modificationDate: kotlin.Long? = null,


    val agreementYearMax: kotlin.Long? = null,


    val agreementRenewalMax: kotlin.Long? = null,


    val sexRestricted: kotlin.String? = null,


    val minimumAgeAuthorized: kotlin.Double? = null,


    val maximumAgeAuthorized: kotlin.Double? = null,


    val maximumContentQuantity: kotlin.Double? = null,


    val maximumContentUnit: kotlin.String? = null,


    val maximumStrengthQuantity: kotlin.Double? = null,


    val maximumStrengthUnit: kotlin.String? = null,


    val maximumDurationQuantity: kotlin.Double? = null,


    val maximumDurationUnit: kotlin.String? = null,


    val otherAddedDocumentInd: kotlin.String? = null,


    val minimumAgeAuthorizedUnit: kotlin.String? = null,


    val maximumAgeAuthorizedUnit: kotlin.String? = null,


    val modificationStatus: kotlin.String? = null,


    val children: kotlin.collections.List<VerseDto>? = null

)

