/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param code
 * @param virtualForm
 * @param routeOfAdministrations
 * @param name
 * @param phaseNumber
 * @param virtualIngredients
 */

data class VmpComponentDto (


    val code: kotlin.String? = null,


    val virtualForm: VirtualFormDto? = null,


    val routeOfAdministrations: kotlin.collections.List<RouteOfAdministrationDto>? = null,


    val name: SamTextDto? = null,


    val phaseNumber: kotlin.Int? = null,


    val virtualIngredients: kotlin.collections.List<VirtualIngredientDto>? = null

)

