/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

/**
 *
 *
 * @param id
 * @param code
 * @param name
 * @param productId
 */

data class VmpGroupStubDto (


    val id: kotlin.String,


    val code: kotlin.String? = null,


    val name: SamTextDto? = null,


    val productId: kotlin.String? = null

)

