name: Publish

on:
  push:
    branches:
      - fix-mutable-map

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Set repo username and password
        env:
          MAVEN_USERNAME: test
          MAVEN_PASSWORD: test
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "repoUsername=${MAVEN_USERNAME}" > ~/.gradle/gradle.properties
          echo "repoPassword=${MAVEN_PASSWORD}" >> ~/.gradle/gradle.properties

      - name: Grant Permissions to gradlew

        run: |
          gradle wrapper
          chmod +x gradlew

      - name: Publish
        run: ./gradlew :kmap:build -x test